<?php

namespace TeamDreamBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarOrderRepository extends EntityRepository
{
}
